'use client';
import React from 'react';
import { useState } from 'react';
import {
  PieChartOutlined,
  DesktopOutlined,
  UserOutlined,
  TeamOutlined,
  FileOutlined,
} from '@ant-design/icons';
import { Layout, Menu, theme, Typography } from 'antd';
import Link from 'next/link';
const { Header, Sider, Content, Footer } = Layout;
// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };
import type { MenuProps } from 'antd';

type MenuItem = Required<MenuProps>['items'][number];

function getItem(
  label: React.ReactNode,
  key: React.Key,
  icon?: React.ReactNode,
  children?: MenuItem[]
): MenuItem {
  return {
    key,
    icon,
    children,
    label,
  } as MenuItem;
}

const items: MenuItem[] = [
  getItem(
    <Link href="/candidates">Candidates</Link>,
    '1',
    <PieChartOutlined />
  ),
  getItem(<Link href="/jobs">Jobs</Link>, '2', <DesktopOutlined />),
  getItem('User', 'sub1', <UserOutlined />, [
    getItem('Tom', '3'),
    getItem('Bill', '4'),
    getItem('Alex', '5'),
  ]),
  getItem('Team', 'sub2', <TeamOutlined />, [
    getItem('Team 1', '6'),
    getItem('Team 2', '8'),
  ]),
  getItem('Files', '9', <FileOutlined />),
];

function MainLayout({ children }: { children: React.ReactNode }) {
  const [collapsed, setCollapsed] = useState(false);
  const {
    token: { colorBgContainer, borderRadiusLG },
  } = theme.useToken();
  return (
    <Layout style={{ minHeight: '100vh' }}>
      <Sider
        collapsible
        collapsed={collapsed}
        onCollapse={(value) => setCollapsed(value)}>
        <div className="demo-logo-vertical" />
        <Menu
          theme="dark"
          defaultSelectedKeys={['1']}
          mode="inline"
          items={items}
        />
      </Sider>
      <Layout>
        <Header
          style={{
            background: colorBgContainer,
          }}>
          <Link href="https://ant.design" target="_blank">
            <Typography.Text
              strong
              style={{
                fontSize: '24px',
                color: '#4096ff',
              }}>
              Cefalo Bangladesh
            </Typography.Text>
          </Link>
        </Header>
        <Content style={{ margin: '16px', height: '100%' }}>
          <div
            style={{
              padding: 24,
              height: '100%',
              minHeight: 400,
              background: colorBgContainer,
              borderRadius: borderRadiusLG,
            }}>
            {children}
          </div>
        </Content>
        <Footer style={{ textAlign: 'center' }}>
          Cefalo AS ©{new Date().getFullYear()} Created by Cefalo
        </Footer>
      </Layout>
    </Layout>
  );
}

export default MainLayout;
